config/routes.rb
# This file is a part of Redmine Resources (redmine_resources) plugin,
# resource allocation and management for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_resources is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_resources is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_resources.  If not, see <http://www.gnu.org/licenses/>.

resources :resource_bookings do
  get :issues_autocomplete, on: :collection
  post :split, on: :member
end

match 'resource_bookings/new', to: 'resource_bookings#new', via: :post
match 'resource_bookings/:id', to: 'resource_bookings#update', via: :post, id: /\d+/

get '/projects/:project_id/resources', to: 'resource_bookings#index', as: 'project_resource_bookings'

app/models/resource_booking.rb
# This file is a part of Redmine Resources (redmine_resources) plugin,
# resource allocation and management for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_resources is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_resources is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_resources.  If not, see <http://www.gnu.org/licenses/>.

class ResourceBooking < ActiveRecord::Base
  include Redmine::SafeAttributes
  include Redmine::Utils::DateCalculation

  belongs_to :project
  belongs_to :assigned_to, class_name: 'Principal'
  belongs_to :issue
  belongs_to :author, class_name: 'User'

  acts_as_event(
    title: Proc.new { |o| o.event_title },
    datetime: :created_at,
    project_key: "#{Project.table_name}.id",
    url: Proc.new { |o| o.url_options },
    author: Proc.new { |o|  o.author },
    description: Proc.new { |o| o.event_description }
  )

  if ActiveRecord::VERSION::MAJOR >= 4
    acts_as_activity_provider(
      type: 'resource_bookings',
      permission: :view_resources,
      timestamp: "#{table_name}.created_at",
      author_key: "#{table_name}.author_id",
      scope: eager_load(:project, :assigned_to, :issue, :author)
    )
  else
    acts_as_activity_provider(
      type: 'resource_bookings',
      permission: :view_resources,
      timestamp: "#{table_name}.created_at",
      author_key: "#{table_name}.author_id",
      find_options: { include: [:project, :assigned_to, :issue, :author] }
    )
  end

  attr_protected :id if ActiveRecord::VERSION::MAJOR <= 4
  safe_attributes 'project_id', 'assigned_to_id', 'issue_id', 'start_date', 'end_date', 'hours_per_day', 'notes'

  validates :project_id, :assigned_to_id, :start_date, :hours_per_day, presence: true
  validates :hours_per_day, numericality: { allow_nil: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 24 }
  validate :check_interval
  validate :check_issue_params # Adds warnings instead of errors

  after_create :send_create_notification
  after_update :send_update_notification

  scope :between, lambda { |from, to|
    condition_sql = <<-SQL.squish
      #{table_name}.start_date >= :from AND #{table_name}.start_date <= :to OR
      :from >= #{table_name}.start_date AND :from <= #{table_name}.end_date
    SQL
    where(condition_sql, from: from.to_datetime, to: to.to_datetime)
  }

  scope :visible, lambda {
    eager_load(:project).where(ResourceBooking.visible_condition)
  }

  def self.allowed_projects
    Project.active.visible
  end

  def self.visible_condition(user = User.current)
    user.reload
    if user.admin?
      '(1=1)'
    else
      projects_ids = Project.where(Project.allowed_to_condition(user, :view_resources)).pluck(:id)
      projects_ids.empty? ? "(1=0)" : "#{Project.table_name}.id IN (#{projects_ids.join(',')})"
    end
  end

  def get_end_date
    end_date || start_date
  end

  def can_add_to?(resource_bookings)
    resource_bookings.all? { |rb| !self.interval.overlaps?(rb.interval) }
  end

  def interval
    (start_date.to_date..get_end_date.to_date)
  end

  def working_days_amount
    interval.sum { |date| non_working_week_days.include?(date.cwday) ? 0 : 1 }
  end

  def total_days
    (get_end_date.to_date - start_date.to_date).to_i + 1
  end

  def total_hours
    working_days_amount * hours_per_day
  end

  def notified_users
    [author, assigned_to].uniq
  end

  def recipients
    notified_users.map(&:mail)
  end

  def email_users
    Redmine::VERSION.to_s < '4.0' ? recipients : notified_users
  end

  def notify?
    @notify != false
  end

  def notify=(arg)
    @notify = arg
  end

  def event_title
    related   = issue if issue && issue.visible?
    related ||= project
    "#{l_hours(total_hours)} (#{related.event_title})"
  end

  def event_description
    "#{l(:label_resource_booking_added)} - #{l(:label_resources_assigned_to_user)}: #{assigned_to}"
  end

  def url_options
    options = {
      controller: 'resource_bookings',
      action: 'index',
      set_filter: 1,
      f: [:project_id, :assigned_to_id, :issue_id],
      op: { project_id: '=', assigned_to_id: '=' },
      v: { project_id: [project_id], assigned_to_id: [assigned_to_id] },
      months: distance_in_months,
      date_from: start_date.to_date
    }

    if issue_id
      options[:op][:issue_id] = '='
      options[:v][:issue_id] = [issue_id]
    else
      options[:op][:issue_id] = '!*'
    end

    options
  end

  def distance_in_months
    distance_in_days = get_end_date - start_date
    distance_in_days > 0 ? (distance_in_days / 1.month).ceil : 1
  end

  def warnings
    @warnings ||= ActiveModel::Errors.new(self)
  end

  private

  def check_interval
    if start_date && end_date && end_date < start_date
      errors.add(:end_date, :greater_than_or_equal_to_start_date)
    end
  end

  def check_issue_params
    if !expired? && issue.try(:due_date) && issue.due_date < get_end_date.to_date
      warnings.add(:end_date, :less_than_or_equal_to_issue_due_date, due_date: format_date(issue.due_date))
    end

    if total_time_exceeds_estimated_time?
      warnings.add(:base, :total_time_exceeds_estimated_time)
    end
  end

  def total_time_exceeds_estimated_time?
    start_date &&
      issue.try(:estimated_hours) &&
      hours_per_day &&
      issue.estimated_hours < issue_assignments_total_time
  end

  def issue_assignments_total_time
    self.class.where(issue_id: issue.id).where('id != ?', id).to_a.sum(&:total_hours) + total_hours
  end

  def expired?
    get_end_date.to_date < User.current.today
  end

  def send_create_notification
    if notify? && Setting.notified_events.include?('resource_updated')
      ResourceBookingsMailer.deliver_resource_booking_create(self)
    end
  end

  def send_update_notification
    if notify? && Setting.notified_events.include?('resource_updated')
      ResourceBookingsMailer.deliver_resource_booking_update(self)
    end
  end
end

app/controllers/resource_bookings_controller.rb
# This file is a part of Redmine Resources (redmine_resources) plugin,
# resource allocation and management for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_resources is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_resources is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_resources.  If not, see <http://www.gnu.org/licenses/>.

class ResourceBookingsController < ApplicationController
  menu_item :resources

  before_action :require_login, :find_project_by_project_id, :find_user_by_user_id, only: :issues_autocomplete
  before_action :find_optional_project, except: :issues_autocomplete
  before_action :find_resource_booking, only: [:destroy, :split]
  before_action :build_resource_booking_from_params, only: [:new, :create, :edit, :update]
  before_action :set_user_blocks_to_update, only: [:new, :create, :update, :destroy, :split]

  helper :issues
  helper :queries
  include QueriesHelper

  def index
    retrieve_query
    if @query.valid?
      @rb_chart = @query.chart_class.new(@project, @query, params)
    end
  end

  def new
  end

  def create
    if @resource_booking.save
      add_to_flash_resource_booking_warnings
      render_update_chart l(:notice_successful_create)
    else
      render :new
    end
  end

  def edit
    # Run validations (There is no method "validate" in Rails 3)
    @resource_booking.valid?
  end

  def update
    if @resource_booking.save
      add_to_flash_resource_booking_warnings
      render_update_chart l(:notice_successful_update)
    else
      render :edit
    end
  end

  def destroy
    if @resource_booking.destroy
      render_update_chart l(:notice_successful_delete)
    else
      flash.now[:error] = l(:notice_could_not_delete)
      render partial: 'update_chart'
    end
  end

  def split
    split_date = @resource_booking.start_date + params[:split_offset].to_i.days
    new_resource_booking = @resource_booking.dup
    @resource_booking.end_date = split_date - 1.day
    new_resource_booking.start_date = split_date

    ResourceBooking.transaction do
      if @resource_booking.save && new_resource_booking.save
        render_update_chart l(:notice_successful_create)
      else
        flash.now[:error] = l(:error_save_failed)
        render partial: 'update_chart'
        raise ActiveRecord::Rollback
      end
    end
  end

  def issues_autocomplete
    @issues = []
    q = (params[:q] || params[:term]).to_s.strip
    scope = Issue
    scope = scope.includes(:tracker).where(project_id: @project.id) if @project.present?

    if q.present?
      if q.match(/\A#?(\d+)\z/)
        @issues << scope.find_by_id($1.to_i)
      end
    end

    scope = scope.like(q).select_with_sorting_by_groups(@user.id)
    @issues += scope.limit(Issue::SELECT2_ISSUES_LIMIT).to_a
    @issues.compact!

    render json: Issue.build_issues_select2_data(@issues, @user)
  end

  private

  def add_to_flash_resource_booking_warnings
    if @resource_booking.warnings.present?
      flash.now[:warning] = @resource_booking.warnings.full_messages.join('; ')
    end
  end

  def render_update_chart(notice)
    if @user_blocks
      flash.now[:notice] = notice
      render partial: 'update_chart', locals: { resize: true }
    else
      flash[:notice] = notice
      render js: "window.location = '#{index_path}'"
    end
  end

  def set_user_blocks_to_update
    retrieve_query
    @query.add_filter('assigned_to_id', '=', [@resource_booking.assigned_to_id.to_s])
    return unless @query.valid?

    @user_blocks = { @resource_booking.assigned_to_id => RedmineResources::Charts::MonthViewBookingsChart.new(@project, @query) }

    assigned_to_id_was = @resource_booking.assigned_to_id_was
    if assigned_to_id_was && (@resource_booking.assigned_to_id != assigned_to_id_was)
      query = @query.dup
      query.add_filter('assigned_to_id', '=', [assigned_to_id_was.to_s])
      @user_blocks[assigned_to_id_was] = RedmineResources::Charts::MonthViewBookingsChart.new(@project, query)
    end
  end

  def find_resource_booking
    @resource_booking = ResourceBooking.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def build_resource_booking_from_params
    if params[:id].blank?
      @resource_booking = ResourceBooking.new(project: @project, author: User.current)
    else
      return unless find_resource_booking
    end

    @resource_booking.safe_attributes = params[:resource_booking]

    @resource_booking.start_date += params[:start_date_offset].to_i.days if params[:start_date_offset]
    if params[:end_date_offset]
      @resource_booking.end_date = @resource_booking.get_end_date + params[:end_date_offset].to_i.days
    end
  end

  # Retrieve query from session or build a new query
  def retrieve_query
    session_key = :resource_booking_query
    if params[:set_filter] || session[session_key].nil? || session[session_key][:project_id] != (@project ? @project.id : nil)
      # Give it a name, required to be valid
      @query = ResourceBookingQuery.new(name: '_', project: @project)
      @query.build_from_params(params)
      session[session_key] = { project_id: @query.project_id, filters: @query.filters, options: @query.options }
    else
      # retrieve from session
      session[session_key][:options][:date_from] = params[:date_from].to_date if params[:date_from]
      @query = ResourceBookingQuery.new(name: '_', filters: session[session_key][:filters], options: session[session_key][:options])
      @query.project = @project
    end
    @query
  end

  def index_path
    @project.blank? ? resource_bookings_path : project_resource_bookings_path(project_id: @project)
  end

  def find_user_by_user_id
    @user = User.find(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/resource_bookings_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine Resources (redmine_resources) plugin,
# resource allocation and management for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_resources is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_resources is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_resources.  If not, see <http://www.gnu.org/licenses/>.

module ResourceBookingsHelper
  include RedmineResources::Charts::Helpers::ChartHelper

  def warning_messages_for(*objects)
    objects = objects.map { |o| o.is_a?(String) ? instance_variable_get("@#{o}") : o }.compact
    warnings = objects.map { |o| o.warnings.full_messages }.flatten
    render_warning_messages(warnings)
  end

  def render_warning_messages(warnings)
    html = ''
    if warnings.present?
      html << "<div id='warningExplanation' class='warning'><ul>\n"
      warnings.each do |warning|
        html << "<li>#{h warning}</li>\n"
      end
      html << "</ul></div>\n"
    end
    html.html_safe
  end

  def chart_type_options
    options = ResourceBookingQuery::CHART_TYPES.map { |x| [l("label_resources_#{x}"), x] }
    options << [l(:label_resources_week_view_chart_pro), :pro]
    options
  end

  def line_title_type_options
    options = RedmineResources::Charts::MonthViewBookingsChart::LINE_TITLE_TYPES.map { |x| [l("label_resources_#{x}"), x] }
    options << [l(:label_resources_issue_subject_pro), :pro]
    options << [l(:label_resources_hours_per_day_pro), :pro]
    options
  end

  def custom_options_for_select(options, selected_option)
    options_for_select(options,
                       disabled: :pro,
                       selected: selected_option)
  end

  def check_box_with_label(value, label, disabled = false)
    value = :pro
    label = "#{label}_pro"
    disabled = true
    check_box('query', value, id: value, disabled: disabled) + l(label)
  end
end

app/views/resource_bookings/_edit_modal.html.erb
<h3 class="title"><%= l(:label_resources_edit_booking) %></h3>

<%= labelled_form_for @resource_booking, url: { action: :update, project_id: @project }, remote: true, html: { id: 'resource-booking-form', method: :put } do |f| %>
  <%= render partial: 'form', locals: { f: f, update_url: j(edit_path_for(@resource_booking)) } %>

  <p class="buttons">
    <%= delete_link resource_booking_path(@resource_booking, project_id: @project), style: 'float: left;', remote: true, onclick: 'hideModal(this);' %>

    <%= submit_tag l(:button_update), name: nil, onclick: 'hideModal(this);' %>
    <%= submit_tag l(:button_cancel), name: nil, onclick: 'hideModal(this);', type: 'button' %>
  </p>
<% end %>

app/views/resource_bookings/_form.html.erb
<%= error_messages_for 'resource_booking' %>
<%= warning_messages_for 'resource_booking' %>

<div class="box tabular">
  <% projects = ResourceBooking.allowed_projects %>
  <% project = @resource_booking.project || projects.first %>
  <% issue = @resource_booking.issue %>

  <p><%= f.select :project_id, project_tree_options_for_select(projects, selected: project), { required: true }, onchange: "updateResourceBookingFrom('#{update_url}')" %></p>
  <p><%= f.select :assigned_to_id, principals_options_for_select(project.users, @resource_booking.assigned_to), required: true %></p>
  <p>
    <label><%= l(:label_issue) %></label>
    <%# TODO: Use select2_tag when support for the dropdownParent option will be available

        Problem: Select2 input doesn't work when embedded in a modal window
        Link: https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst
        ===
        select2_tag 'resource_booking[issue_id]',
                    options_for_select(issues.map { |issue| [issue, issue.id] }, @resource_booking.issue.try(:id)),
                    include_blank: true,
                    url: issues_autocomplete_resource_bookings_path(project_id: project),
                    allow_clear: true,
                    dropdown_parent: 'ajax-modal'
    %>
    <%= select_tag 'resource_booking[issue_id]', options_for_select([[issue, issue.try(:id)]], issue.try(:id)), include_blank: true %>
    <%= javascript_tag do %>
      $('#resource_booking_issue_id').select2({
        placeholder: '',
        width: '95%',
        allowClear: true,
        templateResult: formatStateWithLineThrough,
        containerCssClass: 'icon icon-issue',
        dropdownParent: $('#ajax-modal'),
        ajax: {
          url: function () {
            return '<%= issues_autocomplete_resource_bookings_path(project_id: project) %>' + '&user_id=' + $('#resource_booking_assigned_to_id').val()
          },
          dataType: 'json',
          delay: 250,
          data: function (params) {
            return { q: params.term };
          },
          processResults: function (data, params) {
            return { results: data };
          },
          cache: true
        }
      });
    <% end %>
  </p>

  <p><%= f.text_field :start_date, value: @resource_booking.start_date.try(:to_date), type: 'date', size: 10, required: true %><%= calendar_for('resource_booking_start_date') %></p>
  <p><%= f.text_field :end_date, value: @resource_booking.end_date.try(:to_date), type: 'date', size: 10 %><%= calendar_for('resource_booking_end_date') %></p>

  <p><%= f.text_field :hours_per_day, required: true %></p>
  <p><%= f.text_area :notes, rows: 8, placeholder: l(:label_resources_leave_comment) %></p>
</div>

app/views/resource_bookings/_new_modal.html.erb
<h3 class="title"><%= l(:label_resources_new_booking) %></h3>

<%= labelled_form_for @resource_booking, url: { action: :create, project_id: @project }, remote: true, html: { id: 'resource-booking-form', method: :post } do |f| %>
  <%= render partial: 'form', locals: { f: f, update_url: j(new_resource_booking_path(project_id: @project)) } %>
  <p class="buttons">
    <%= submit_tag l(:button_create), name: nil, onclick: 'hideModal(this);' %>
    <%= submit_tag l(:button_cancel), name: nil, onclick: 'hideModal(this);', type: 'button' %>
  </p>
<% end %>

app/views/resource_bookings/_query_form.html.erb
<%= form_tag({ controller: 'resource_bookings', action: 'index', project_id: @project, months: params[:months] },
             method: :get, id: 'query_form') do %>

  <%= hidden_field_tag 'set_filter', '1' %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible">
        <legend class="icon icon-expended" onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
        <div style="<%= @query.new_record? ? '' : 'display: none;' %>">
          <%= render partial: 'queries/filters', locals: { query: @query } %>
        </div>
      </fieldset>

      <fieldset id="options" class="collapsible collapsed">
        <legend class="icon icon-collapsed" onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
        <div style="display: none;">
          <table>
            <tr>
              <td><%= label_tag :chart_type, l(:label_resources_chart_type) %></td>
              <td><%= select_tag :chart_type, custom_options_for_select(chart_type_options, @query.chart_type),
                                 onchange: "toggleBlockGroup('chart-type', this.value);" %></td>
            </tr>

            <tr class="chart-type <%= ResourceBookingQuery::MONTH_VIEW_CHART %>" style="display: none;">
              <td><%= label_tag :line_title_type, l(:label_resources_line_title) %></td>
              <td><%= select_tag :line_title_type, custom_options_for_select(line_title_type_options, @query.line_title_type) %></td>
            </tr>
            <tr>
              <td><%= l(:button_show) %></td>
              <td>

                <label for="show_versions">
                  <%= check_box_with_label('show_versions', :label_version_plural) %>
                </label>

                <label for="show_issues" class="chart-type <%= ResourceBookingQuery::MONTH_VIEW_CHART %>" style="display: none;">
                  <%= check_box 'query', 'show_issues', id: 'show_issues' %>
                  <%= l(:label_issue_plural) %>
                </label>

                <label for="show_ghost_bookings" class="chart-type <%= ResourceBookingQuery::MONTH_VIEW_CHART %>" style="display: none;">
                  <%= check_box_with_label('show_ghost_bookings', :label_resources_ghost_bookings) %>
                </label>
              </td>
            </tr>
          </table>
        </div>
      </fieldset>
    </div>

    <% if @query.month_view_chart? %>
      <p class="contextual">
        <%= zoom_link(@rb_chart, :in) %>
        <%= zoom_link(@rb_chart, :out) %>
      </p>
    <% end %>

    <p class="buttons">
      <span class="chart-type <%= ResourceBookingQuery::MONTH_VIEW_CHART %>" style="display: none;">
        <%= text_field_tag 'months', @rb_chart.months, size: 2 %>
        <%= l(:label_months_from) %>
      </span>
      <%= text_field 'query', 'date_from', size: 12, type: 'date' %><%= calendar_for('query_date_from') %>

      <%= hidden_field_tag('zoom', @rb_chart.zoom) if @query.month_view_chart? %>

      <%= link_to_function l(:button_apply), '$("#query_form").submit()', class: 'icon icon-checked' %>
      <%= link_to l(:button_clear), { project_id: @project, set_filter: 1 }, class: 'icon icon-reload' %>
    </p>
  </div>
<% end %>

<%= error_messages_for 'query' %>

<%= javascript_tag do %>
  $(function () {
    $('#chart_type').trigger('change');
  });
<% end %>

app/views/resource_bookings/_update_chart.js.erb
$(function () {
  renderFlashMessages('<%= render_flash_messages %>')

  <% (@user_blocks || {}).each do |user_id, rb_chart| %>
    <% rb_chart.view = self %>
    <% rb_chart.render %>

    updateUserBlock(<%= user_id %>,
                    '<%= j(rb_chart.subjects.html_safe) %>',
                    '<%= j(rb_chart.lines.html_safe) %>',
                    <%= defined?(resize) && resize ? rb_chart.netto_height : 0 %>);

    var columnWidth = <%= rb_chart.column_width %>;
  <% end %>
});

app/views/resource_bookings/edit.js.erb
$('#ajax-modal').html('<%= j(render partial: 'edit_modal') %>');
showModal('ajax-modal', '600px');

<%= render partial: 'update_chart' %>

app/views/resource_bookings/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:add_booking, @project, global: true) %>
    <%= link_to l(:label_resources_new_booking), new_resource_booking_path(project_id: @project), remote: true, method: 'get', class: 'icon icon-add' %>
  <% end %>

  <% if !@query.new_record? && @query.editable_by?(User.current) %>
    <%= link_to l(:button_edit), edit_query_path(@query, gantt: 1), :class => 'icon icon-edit' %>
    <%= delete_link query_path(@query, gantt: 1) %>
  <% end %>
</div>

<h2><%= l(:label_resource_planning) %></h2>

<%= render partial: 'query_form' %>

<% if @query.valid? %>
  <% @rb_chart.view = self %>
  <%= render partial: "resource_bookings/charts/#{@query.chart_type}" %>
<% end %>

<% html_title(l(:label_resources)) -%>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag(:redmine_resources, plugin: 'redmine_resources') %>
  <%= javascript_include_tag(:redmine_resources, plugin: 'redmine_resources') %>
  <%= select2_assets %>
<% end %>

app/views/resource_bookings/new.js.erb
$('#ajax-modal').html('<%= j(render partial: 'new_modal') %>');
showModal('ajax-modal', '600px');

<%= render partial: 'update_chart' if @user_blocks.present? %>